arm64: dts: mediatek: use quoted instead of angled include
arch/arm64/boot/dts/mediatek/shiva.dts:650:10:
error: 'lancelot/cust.dtsi' file not found with <angled> include; use "quotes" instead

Signed-off-by: chickendrop89 <chickendrop89@gmail.com>